# Generated by Django 5.0.4 on 2024-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2b_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="c2btransaction",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="bill_ref_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="command_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="msisdn",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="c2btransaction",
            name="confirmation_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="c2btransaction",
            name="response_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="c2btransaction",
            name="validation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
