# Generated by Django 5.0.4 on 2024-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2b_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="c2btransaction",
            old_name="transaction_id",
            new_name="trans_id",
        ),
        migrations.RenameField(
            model_name="c2btransaction",
            old_name="transaction_time",
            new_name="trans_time",
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="org_account_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="third_party_trans_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="c2btransaction",
            name="transaction_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="c2btransaction",
            name="originator_conversation_id",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
