# Generated by Django 5.0.4 on 2024-05-17 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("c2b_api", "0002_rename_transaction_id_c2btransaction_trans_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="c2btransaction",
            old_name="originator_conversation_id",
            new_name="originator_coversation_id",
        ),
    ]
